using Gaida.Core.Utils;

namespace Gaida.Tests;

public class TitleNormalizerTests
{
    [Fact]
    public void DropsNoiseBracketsAndSplitsArtistFromTitle()
    {
        var normalized = TitleNormalizer.Normalize("Rammstein - Sonne (Official Video)");

        Assert.Contains(new TitleCandidate("Rammstein", "Sonne"), normalized.Candidates);
        Assert.Empty(normalized.RenditionTags);
        Assert.Equal(0, normalized.UnknownTags);
    }

    [Fact]
    public void KeepsBothScriptsOfADualScriptTitle()
    {
        var normalized = TitleNormalizer.Normalize("Lia - Mitnichariu/ Лия - Митничарю");

        // The Cyrillic half is what reaches OriginalTitle exactly; the Latin half is what reaches
        // RomanizedTitle. Scoring every candidate and taking the max is what makes the exact hit available.
        Assert.Contains(new TitleCandidate("Лия", "Митничарю"), normalized.Candidates);
        Assert.Contains(new TitleCandidate("Lia", "Mitnichariu"), normalized.Candidates);
    }

    [Fact]
    public void StripsATrailingYearWithoutEatingACommaInTheTitle()
    {
        var normalized = TitleNormalizer.Normalize("EMANUELA - ARE, DARPAY / Емануела - Аре, дърпай, 2019");

        Assert.Contains(new TitleCandidate("Емануела", "Аре, дърпай"), normalized.Candidates);
        Assert.Contains(new TitleCandidate("EMANUELA", "ARE, DARPAY"), normalized.Candidates);
    }

    [Fact]
    public void DoesNotSplitASeparatorInsideAName()
    {
        var normalized = TitleNormalizer.Normalize("AC/DC - Back in Black");

        Assert.Contains(new TitleCandidate("AC/DC", "Back in Black"), normalized.Candidates);
        Assert.DoesNotContain(normalized.Candidates, candidate => candidate.Title == "AC");
    }

    [Fact]
    public void DropsAPipedNoiseSegmentInsteadOfWeighingIt()
    {
        var normalized = TitleNormalizer.Normalize("Rammstein - Sonne | Official Video");

        Assert.Contains(new TitleCandidate("Rammstein", "Sonne"), normalized.Candidates);
        Assert.DoesNotContain(normalized.Candidates, candidate => candidate.Title.Contains("Official"));
    }

    [Fact]
    public void StripsTagsBeforeWeighingTheHalves()
    {
        // Measured raw, the tag's weight alone sinks the balance rule and the split never happens.
        var normalized = TitleNormalizer.Normalize("Artist - Title (Official Video) / Артист - Заглавие");

        Assert.Contains(new TitleCandidate("Artist", "Title"), normalized.Candidates);
        Assert.Contains(new TitleCandidate("Артист", "Заглавие"), normalized.Candidates);
    }

    [Fact]
    public void RecordsARenditionTagAndDropsItFromTheText()
    {
        var normalized = TitleNormalizer.Normalize("Sonne (Instrumental)");

        Assert.Contains(new TitleCandidate(string.Empty, "Sonne"), normalized.Candidates);
        Assert.Equal(["instrumental"], normalized.RenditionTags);
    }

    [Fact]
    public void TakesTheArtistFromAnAutoGeneratedChannel()
    {
        var normalized = TitleNormalizer.Normalize("Sonne", "Rammstein - Topic");

        Assert.Contains(new TitleCandidate("Rammstein", "Sonne"), normalized.Candidates);
    }

    [Fact]
    public void ReadsTheLibrarySideWithTheSameClassifier()
    {
        var (text, tags) = TitleNormalizer.NormalizeLibrary("Sonne (Instrumental)");

        Assert.Equal("Sonne", text);
        Assert.Equal(["instrumental"], tags);
    }

    [Fact]
    public void TreatsARemasterAsTheSamePerformance()
    {
        // Load-bearing: renditions only offer untagged library tracks, so a remastered file classified as a
        // rendition would be permanently unofferable.
        var (_, tags) = TitleNormalizer.NormalizeLibrary("Sonne (Remastered)");

        Assert.Empty(tags);
    }
}