<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Gaida\Platforms\Gaida.Platforms.MusicDatabase\Gaida.Platforms.MusicDatabase.csproj" />
    <ProjectReference Include="..\Gaida\Platforms\Gaida.Platforms.Spotify\Gaida.Platforms.Spotify.csproj" />
    <ProjectReference Include="..\Gaida\Platforms\Gaida.Platforms.YouTube\Gaida.Platforms.YouTube.csproj" />
    <ProjectReference Include="..\Gaida\Gaida.Core\Gaida.Core.csproj" />
    <ProjectReference Include="../DSharpPlus/DSharpPlus/DSharpPlus.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
  </ItemGroup>

</Project>
